# Generated by Django 3.0.4 on 2020-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='verb',
            field=models.CharField(choices=[('F', 'Fetch'), ('P', 'Provide'), ('T', 'Transport'), ('N', 'Notify')], default='F', max_length=3, verbose_name='Action on the title, (eg, GET)'),
        ),
    ]
