# Generated by Django 3.0.4 on 2020-03-29 10:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0002_participant_metadata")]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        )
    ]
