# Generated by Django 3.0.4 on 2020-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0005_auto_20200331_1646")]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
