# Generated by Django 3.0.4 on 2021-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0007_auto_20200516_1418")]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="currency",
            field=models.CharField(
                blank=True, default="SEK", max_length=3, verbose_name="Default Currency"
            ),
        )
    ]
