repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
