language: python
dist: bionic
python:
  - 3.7.5
services:
  - postgresql
install:
  - pip install -q -r requirements.txt
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-client-10
      - postgresql-10-postgis-2.4
env:
  global:
    - PGPORT=5433
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database travis_ci_test;' -U postgres
  - mv quarantined_backend/local_settings_travis.py quarantined_backend/local_settings.py
  - python manage.py migrate --noinput
  - python manage.py collectstatic  --noinput
script:
  - python manage.py test
