dist: bionic
sudo: required
language: python
python:
  - 3.7.5
install:
  - pip install -q -r requirements.txt
services:
  - postgresql
before_script:
  - sudo apt-get install -y binutils libproj-dev gdal-bin
  - psql -c 'create database travis_ci_test;' -U postgres
  - mv quarantined_backend/local_settings_travis.py quarantined_backend/local_settings.py
  - python manage.py migrate --noinput
  - python manage.py collectstatic  --noinput
script:
  - python manage.py test
