# Generated by Django 3.0.4 on 2020-03-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="Name of ability"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crisis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField()),
            ],
        ),
    ]
