# Generated by Django 3.0.4 on 2020-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crisis",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("T", "Transit"),
                            ("F", "Finished"),
                            ("C", "Cancelled"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("G", "Grocery"), ("M", "Medicine")], max_length=2
                    ),
                ),
                ("deadline", models.DateTimeField(null=True)),
                ("description", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RequestAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_created=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Assigned"),
                            ("D", "Dropped"),
                            ("C", "Completed"),
                        ],
                        max_length=2,
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("did_complete", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
    ]
