# Generated by Django 3.0.4 on 2020-03-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crisis", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        )
    ]
