# Generated by Django 3.0.4 on 2020-03-21 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crisis", "0002_participant_created_at")]

    operations = [
        migrations.RemoveField(model_name="participant", name="latitude"),
        migrations.RemoveField(model_name="participant", name="longitude"),
        migrations.AddField(
            model_name="participant",
            name="position",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
