# Generated by Django 3.0.4 on 2020-03-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        ("crisis", "0002_auto_20200328_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assignee",
                to="management.Participant",
            ),
        )
    ]
