# Generated by Django 3.0.4 on 2020-04-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crisis", "0003_auto_20200330_1054")]

    operations = [
        migrations.AlterField(
            model_name="requestassignment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_assignee",
                to="crisis.Request",
            ),
        )
    ]
