# Generated by Django 3.0.4 on 2020-03-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_ability_verb"),
        ("crisis", "0003_auto_20200321_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="abilities",
            field=models.ManyToManyField(null=True, to="management.Ability"),
        )
    ]
