# Generated by Django 3.0.4 on 2020-04-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crisis", "0004_auto_20200401_1821")]

    operations = [
        migrations.RemoveField(model_name="requestassignment", name="assigned_at")
    ]
