# Generated by Django 3.0.4 on 2020-03-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_ability_verb"),
        ("crisis", "0005_auto_20200323_2113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="abilities",
            field=models.ManyToManyField(
                blank=True, default=[], null=True, to="management.Ability"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="crisis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crisis.Crisis"
            ),
        ),
    ]
