# Generated by Django 3.0.4 on 2020-04-04 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("crisis", "0005_remove_requestassignment_assigned_at")]

    operations = [
        migrations.AddField(
            model_name="requestassignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
