# Generated by Django 3.0.4 on 2020-04-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_auto_20200404_1112"),
        ("crisis", "0006_requestassignment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestassignment",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_assignment",
                to="management.Participant",
            ),
        ),
        migrations.AlterField(
            model_name="requestassignment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_assignment",
                to="crisis.Request",
            ),
        ),
    ]
