# Generated by Django 3.0.4 on 2020-03-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crisis", "0007_auto_20200323_2158")]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("T", "Transit"),
                            ("F", "Finished"),
                            ("C", "Cancelled"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("G", "Grocery"), ("M", "Medicine")], max_length=2
                    ),
                ),
                ("deadline", models.DateTimeField(null=True)),
                ("description", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.RemoveField(model_name="participant", name="abilities"),
        migrations.RemoveField(model_name="participant", name="is_available"),
        migrations.AddField(
            model_name="crisis",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name="RequestAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_created=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Assigned"),
                            ("D", "Dropped"),
                            ("C", "Completed"),
                        ],
                        max_length=2,
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("did_complete", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crisis.Participant",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crisis.Request"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="request",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assignee",
                to="crisis.Participant",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="crisis.Participant",
            ),
        ),
    ]
