# Generated by Django 3.0.4 on 2020-04-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_auto_20200404_1112"),
        ("crisis", "0007_auto_20200406_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestassignment",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_assignment",
                to="management.Participant",
            ),
        )
    ]
