# Generated by Django 3.0.4 on 2020-04-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crisis", "0008_auto_20200406_1113")]

    operations = [
        migrations.AlterModelTable(name="crisis", table="crisis_crisis"),
        migrations.AlterModelTable(name="request", table="crisis_request"),
        migrations.AlterModelTable(
            name="requestassignment", table="crisis_requestassignment"
        ),
    ]
